### ISSUE TITLE
Is there a way to insert instead of replace existing values?

### ISSUE THREAD

**Issue by bmorton** [rdleal/intervalst#1] opened 2023-08-23 18:44 UTC
Hey, thanks for this fantastic library!  I noticed that when I insert two records at the same exact times, the record is replaced.  But if I offset it by 1 nanosecond, I can get both records back from `AllIntersections`.

It seems like this is by design, but my use-case could have exact timestamp overlaps and I want `AllIntersections` to return both records.

Is this a change that you'd be interested in?  Can it be specified as an option for `time.Time` somehow if other types prefer the `upsert` approach?  I was going to look into what it would take, but wanted to run the idea by you first to make sure that I'm not missing something fundamental.

**Comment by rdleal** [comment] 2023-08-28 19:56
Hey, @bmorton thanks for using the library and bringing feedback about it.

That's indeed by design, since the `Insert` method will replace the key value if it already exists. Probably `Insert` was not a happy name to choose for the current behavior. `Upsert` seems to be more appropriate. Changing the behavior of the `Insert` would cause a breaking change, though. So I would create another method for adding more than one value for the same key (haven't thought about a good name for it yet)

That would requires a few changes, like changing the field `val` of the type `interval` to be a slice of `V` [here](https://github.com/rdleal/intervalst/blob/main/interval/interval.go#L48C1-L52C2):

```go
type interval[V, T any] struct {
	start T
	end   T
	val   []V
}
```

Also, it would require some changes on the current `Insert` method to keep the current (`upsert`) behavior.

I think that's a fair feature, and maybe even more common than the `upsert` one. I believe I'll get a change to add this this week.

**Comment by rdleal** [comment] 2023-09-10 02:21
@bmorton I've added a new type `MultiValueSearchTree` to the library. With this type you would be able to insert multiple values for the same interval key. 

You can instantiate that type:
```go
st := interval.NewMultiValueSearchTree[string](cmpFn) // Definition of cmpFn omitted for brevity
```

then insert multiple values at once:
```go
err := st.Insert(start, end, "val1", "val2", "val3") // start and end definition omitted for brevity
```

or insert multiple values one at a time:
```go
err := st.Insert(start, end, "val1")

// ...

err := st.Insert(start, end, "val2")

// ...

err := st.Insert(start, end, "val3")
```

Either way you get the same result, the `start` and `end` interval key with a list of values:

```go
vals, ok := st.AllIntersections(start, end)
// vals = ["val1", "val2", "val3"]
```

I'm still refactoring some things before officially launching this version, but you can test it by download the package from the branch "multi-value":
```sh
$ go get github.com/rdleal/intervalst/interval@multi-value
```

Also the `Insert` doesn't work like a upsert for the type `MultiValueSearchTree`. I added a specific method for this behavior called `Upsert`.

What do you think?

**Comment by rdleal** [comment] 2023-09-19 01:28
@bmorton The changes are on `main` branch. I should be generating a tag for the changes this week.

**Comment by rdleal** [comment] 2023-09-20 22:37
@bmorton tag `v1.1.0` contains the changes that exposes the type `MultiValueSearchTree`, allowing you to associate values to the same interval key. That should be enough for you use case.

I'm closing this issue. Feel free to open another issue if you still don't have your use case covered, or found any problem with the package.

**Closed by rdleal** 2023-09-20 22:37 UTC

**Comment by bmorton** [comment] 2023-09-20 23:16
This is really cool, thanks for getting this pushed out!  I'm sorry for the radio silence on my end, I'll give it a deeper dive soon.
